"use client";

import { useState } from "react";

type Page = { section: string; titleZh: string; titleEn: string; zh: string; en: string; reference: string; scene: string };

const pages: Page[] = [
  { section: "起初 · In the Beginning", titleZh: "神创造天地", titleEn: "God Creates the World", zh: "起初，神创造天地。那时，地是空虚混沌，深渊上面一片黑暗；但神的灵运行在水面上。神说：“要有光。”光就出现了。神把光暗分开，称光为昼，称暗为夜。这个故事一开始就告诉我们：光、生命、秩序和美好，都从创造主神而来。", en: "In the beginning, God created the heavens and the earth. The earth was formless and empty, darkness covered the deep waters, and the Spirit of God moved over the waters. Then God said, “Let there be light,” and there was light. God separated the light from the darkness, calling the light day and the darkness night. From the very beginning, light, life, order, and goodness come from God our Creator.", reference: "创世记 Genesis 1:1–5", scene: "light" },
  { section: "创造 · Creation", titleZh: "一个有秩序的世界", titleEn: "A World Made with Order", zh: "神创造天空、海洋和陆地；祂使地长出青草、菜蔬和结果子的树。祂又创造日、月和星辰，叫它们管理昼夜。第五天，神创造海里的鱼和空中的鸟；第六天，祂创造地上的牲畜、昆虫和野兽。神每一次创造以后，都看着是好的。", en: "God made the sky, the seas, and the dry land. He caused grass, plants, and fruit trees to grow. He made the sun, moon, and stars to mark day and night. On the fifth day, God made fish and birds; on the sixth day, He made animals that live on the earth. After each part of creation, God saw that it was good.", reference: "创世记 Genesis 1:6–25", scene: "garden" },
  { section: "人的开始 · The Beginning of Humanity", titleZh: "神按自己的形象造人", titleEn: "Made in God’s Image", zh: "在创造的最后，神按着自己的形象造人，造男造女。祂赐福给他们，也把管理地上受造物的责任交给他们。人不是偶然出现的；每一个人都有神所赐的价值，也受托好好照顾神所创造的世界。神看着一切所造的都甚好。", en: "At the end of creation, God made people in His own image—male and female. He blessed them and gave them the responsibility to care for the living things on earth. People are not an accident. Every person has God-given worth and is entrusted to care well for God’s world. God saw everything He had made, and it was very good.", reference: "创世记 Genesis 1:26–31", scene: "people" },
  { section: "伊甸园 · The Garden", titleZh: "丰盛，也有界限", titleEn: "Abundance and a Boundary", zh: "神把亚当安置在伊甸园，使他修理、看守园子。园中有各样美好的树，果子可以作食物。神说：“园中各样树上的果子，你可以随意吃；只是分别善恶树上的果子，你不可吃。”神给人丰富的供应，也给人清楚的界限，邀请人相信祂的话是好的。", en: "God placed Adam in the garden of Eden to work it and take care of it. The garden was full of beautiful trees with good fruit to eat. God said, “You are free to eat from any tree in the garden; but you must not eat from the tree of the knowledge of good and evil.” God gave people abundance, and also a clear boundary, inviting them to trust that His words are good.", reference: "创世记 Genesis 2:8–17", scene: "tree" },
  { section: "人的选择 · A Human Choice", titleZh: "人选择不听从神", titleEn: "Choosing Not to Obey", zh: "蛇引诱夏娃，使她怀疑神的话。夏娃看见分别善恶树的果子好作食物、悦人眼目，又能使人有智慧，就摘下来吃了；她也给亚当，亚当也吃了。他们没有相信神的命令，反而选择自己决定什么是对、什么是错。", en: "The serpent tempted Eve and made her question God’s word. She saw that the fruit of the tree was good for food, pleasing to the eye, and desirable for gaining wisdom. So she ate it and gave some to Adam, and he ate it too. Instead of trusting God’s command, they chose to decide for themselves what was right and wrong.", reference: "创世记 Genesis 3:1–7", scene: "choice" },
  { section: "破裂 · Brokenness", titleZh: "罪带来羞耻与躲避", titleEn: "Sin Brings Shame and Hiding", zh: "亚当和夏娃吃了果子以后，发现自己赤身露体，就感到羞耻。当他们听见神的声音，就躲起来。神问亚当：“你在哪里？”他们害怕，也开始彼此推卸责任。罪使人躲避神，也让人与人之间的关系破裂。最后，他们离开了伊甸园。", en: "After Adam and Eve ate the fruit, they realized they were naked and felt ashamed. When they heard God, they hid. God called to Adam, “Where are you?” They were afraid and began to blame each other. Sin makes people hide from God and breaks relationships with one another. In the end, they left the garden of Eden.", reference: "创世记 Genesis 3:8–24", scene: "shadow" },
  { section: "罪的扩散 · Sin Spreads", titleZh: "该隐与亚伯", titleEn: "Cain and Abel", zh: "该隐和亚伯都向神献祭。该隐因神看中亚伯和他的供物，就大大地发怒。神提醒该隐，罪伏在门前，他应当制伏罪；但该隐没有听从。他把亚伯带到田间，并杀了自己的弟弟。嫉妒和愤怒若不被面对，可能会变成伤害别人的行动。", en: "Cain and Abel both brought offerings to God. Cain became very angry when God looked with favor on Abel and his offering. God warned Cain that sin was waiting at the door and that he should master it. But Cain did not listen. He took Abel to a field and killed his brother. Jealousy and anger, when left unchecked, can grow into actions that hurt others.", reference: "创世记 Genesis 4:1–16", scene: "field" },
  { section: "洪水之前 · Before the Flood", titleZh: "挪亚在神眼前蒙恩", titleEn: "Noah Finds Favor", zh: "人的罪恶越来越大，地上也充满强暴。神看见人败坏了行为，就决定审判这败坏的世界。但是，挪亚在耶和华眼前蒙恩。经文说，挪亚是个义人，并且与神同行。当世界越来越远离神时，挪亚选择相信神、跟随神。", en: "Human evil grew greater and the earth was full of violence. God saw that people had corrupted their ways, and He decided to judge the broken world. Yet Noah found favor in the eyes of the Lord. Scripture says that Noah was a righteous man who walked with God. While the world moved farther from God, Noah chose to trust and follow Him.", reference: "创世记 Genesis 6:5–13", scene: "rain" },
  { section: "方舟 · The Ark", titleZh: "神预备拯救的道路", titleEn: "God Prepares a Way of Rescue", zh: "神告诉挪亚，洪水将要临到地上；祂也吩咐挪亚造一只方舟，带着家人和各类活物进入方舟，好保全生命。挪亚没有看见洪水，却相信神所说的话。他照着神所吩咐的一切去做。神的审判是真实的；神的拯救也是真实的。", en: "God told Noah that a flood was coming, and commanded him to build an ark. Noah was to bring his family and living creatures into it so that life would be preserved. Noah had not seen the flood, but he trusted what God had said. He did everything God commanded. God’s judgment is real, and so is God’s rescue.", reference: "创世记 Genesis 6:14–22; 7:1–10", scene: "ark" },
  { section: "洪水 · The Flood", titleZh: "神记念挪亚", titleEn: "God Remembers Noah", zh: "洪水临到地上，水势浩大。方舟以外的生命都灭绝了；但方舟里的挪亚一家和活物得以保全。后来，经文说：“神记念挪亚。”神使风吹地，洪水渐渐退去。方舟停住，地也慢慢干了。在审判中，神没有忘记祂所拯救的人。", en: "The flood came upon the earth and the waters rose greatly. Life outside the ark perished, but Noah’s family and the animals in the ark were kept safe. Then Scripture says, “God remembered Noah.” God sent a wind over the earth, and the waters began to go down. The ark came to rest and the land slowly dried. In judgment, God did not forget those He rescued.", reference: "创世记 Genesis 7:11–24; 8:1–19", scene: "dove" },
  { section: "应许 · Promise", titleZh: "彩虹：神守约的记号", titleEn: "The Rainbow: A Sign of God’s Promise", zh: "挪亚出了方舟后，筑坛敬拜神。神与挪亚、他的后代和一切活物立约，答应不再用洪水毁灭全地。神把彩虹放在云中，作为这个约的记号。彩虹提醒我们：神是公义的，祂认真对待罪；神也是信实和怜悯的，祂守住自己的应许。", en: "After Noah left the ark, he built an altar and worshiped God. God made a covenant with Noah, his descendants, and every living creature. He promised never again to destroy the whole earth with a flood. God placed the rainbow in the clouds as the sign of this covenant. The rainbow reminds us that God is just and takes sin seriously; He is also faithful, merciful, and keeps His promises.", reference: "创世记 Genesis 8:20–22; 9:8–17", scene: "rainbow" },
];

const sceneArt: Record<string, string> = { light: "✦", garden: "❋", people: "◐", tree: "♧", choice: "◒", shadow: "◑", field: "⌁", rain: "☂", ark: "⌒", dove: "⌁", rainbow: "◜" };

export default function Home() {
  const [pageIndex, setPageIndex] = useState(0);
  const page = pages[pageIndex];
  const go = (direction: number) => setPageIndex((current) => Math.min(Math.max(current + direction, 0), pages.length - 1));
  return <main>
    <div className="grain" aria-hidden="true" />
    <header className="topbar"><a className="brand" href="#top" aria-label="Walk Through Bible home"><span className="brand-mark">W</span><span>Walk Through Bible</span></a><span className="volume">第一册 · Volume One</span></header>
    <section className="hero" id="top"><p className="eyebrow">BIBLE STORIES · 中英文双语电子书</p><h1>起初，<em>故事开始。</em></h1><p className="hero-copy">从创造、伊甸园、人的选择，到挪亚方舟与彩虹之约。<br />一段可以慢慢读，也值得反复回看的圣经故事。</p><a className="begin" href="#book">开始阅读 <span>↓</span></a></section>
    <section className="book-area" id="book" aria-label="Bible story reader"><div className="reader-label"><span>第 {String(pageIndex + 1).padStart(2, "0")} 页</span><span>{page.section}</span></div><article className={`page scene-${page.scene}`}><div className="art" aria-hidden="true"><span>{sceneArt[page.scene]}</span></div><div className="page-content"><p className="chapter">{page.section}</p><h2>{page.titleZh}</h2><h3>{page.titleEn}</h3><div className="rule" /><p className="story zh">{page.zh}</p><p className="story en">{page.en}</p><p className="reference">{page.reference}</p></div></article><nav className="navigation" aria-label="Page navigation"><button onClick={() => go(-1)} disabled={pageIndex === 0}>← 上一页 <span>Previous</span></button><div className="dots" aria-label={`Page ${pageIndex + 1} of ${pages.length}`}>{pages.map((_, index) => <button key={index} className={index === pageIndex ? "active" : ""} onClick={() => setPageIndex(index)} aria-label={`Go to page ${index + 1}`} />)}</div><button onClick={() => go(1)} disabled={pageIndex === pages.length - 1}><span>Next</span> 下一页 →</button></nav></section>
    <footer>Walk Through Bible · 让圣经的大故事，一页一页走进心里。</footer>
  </main>;
}
